name: Sync Upstream and Convert to Traditional Chinese

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜執行
  workflow_dispatch:

jobs:
  sync-and-convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Configure Git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      
      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/PlexPt/factorio-chinese.git
          git fetch upstream
          
      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main --no-edit || {
            echo "Merge conflict occurred. Aborting merge."
            git merge --abort
            exit 1
          }
      
      - name: Install OpenCC
        run: |
          sudo apt-get update
          sudo apt-get install -y opencc
      
      - name: Setup zh-TW directory
        run: |
          rm -rf locale/zh-TW
          mkdir -p locale/zh-TW
      
      - name: Convert files
        run: |
          if [ -d "locale/zh-CN" ] && [ "$(ls -A locale/zh-CN/*.cfg 2>/dev/null)" ]; then
            for file in locale/zh-CN/*.cfg; do
              filename=$(basename "$file")
              echo "Converting $filename using s2twp"
              opencc -i "$file" -o "locale/zh-TW/$filename" -c s2twp.json
            done
            echo "Conversion completed"
          else
            echo "No .cfg files found in zh-CN directory"
            exit 0
          fi
      
      - name: Commit and push changes
        run: |
          if git status --porcelain | grep -q "locale/zh-TW/"; then
            git add locale/zh-TW/
            git commit -m "chore: sync upstream and convert zh-CN to zh-TW (using s2twp) [skip ci]"
            git push origin main
          else
            echo "No changes to commit"
          fi

permissions:
  contents: write
